name: Update GitHub Stats in README

on:
  schedule:
    - cron: '0 0 * * *'  # Se ejecuta todos los días a medianoche
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch GitHub Stats from JRueda2001
        env:
          OTHER_GH_USER: "JRueda2001"
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=${OTHER_GH_USER}&count_private=true&theme=dark"
          curl -o streak.svg "https://github-readme-streak-stats.herokuapp.com/?user=${OTHER_GH_USER}&theme=dark"
          curl -o langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=${OTHER_GH_USER}&count_private=true&layout=compact&theme=dark"

      - name: Check Access to Private Repository
        env:
          GH_PAT_JRUEDA: ${{ secrets.GH_PAT_JRUEDA }}
        run: |
          echo"${GH_PAT_JRUEDA}"
